### ISSUE TITLE
runtime error on release build

### ISSUE THREAD

**Issue by enurlyx** [buggins/dlangui#103] opened 2015-11-07 18:38 UTC
Running "Hello World" (release build) results in a crash and errormessage at the start:

```object.Error@(0):Access Violation```

The debug version runs fine.

System: Win8.1 64bit  dmd 2.069.0

Build command:
```
C:\Users\enurlyx\Downloads\dlangui\examples\helloworld>dub run --build=release
Selected package dsfml ~master does not match the dependency specification >=2.1
.0 <3.0.0 in package dsfml. Need to "dub upgrade"?
Selected package dsfml ~master does not match the dependency specification >=2.1
.0 <3.0.0 in package dsfml:window. Need to "dub upgrade"?
Selected package dsfml ~master does not match the dependency specification >=2.1
.0 <3.0.0 in package dsfml. Need to "dub upgrade"?
Selected package dsfml ~master does not match the dependency specification >=2.1
.0 <3.0.0 in package dsfml. Need to "dub upgrade"?
Selected package dsfml ~master does not match the dependency specification >=2.1
.0 <3.0.0 in package dsfml. Need to "dub upgrade"?
Performing "release" build using dmd for x86.
derelict-util 2.0.4: target for configuration "library" is up to date.
derelict-ft 1.0.2: target for configuration "library" is up to date.
derelict-gl3 1.0.16: target for configuration "library" is up to date.
derelict-sdl2 1.9.7: target for configuration "library" is up to date.
dlib 0.7.0: target for configuration "library" is up to date.
gl3n 1.2.0: target for configuration "library" is up to date.
dlangui 0.6.39: target for configuration "default" is up to date.
helloworld ~master: building configuration "application"...
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Copying files for dlangui...
Running .\bin\helloworld.exe
```

**Comment by buggins** [comment] 2015-11-10 12:35
reproduced

**Comment by buggins** [comment] 2015-11-11 09:12
Caused by AccessViolation inside DerelictFT.load

**Comment by buggins** [comment] 2015-11-11 11:00
App crashes on windows if compiled for x86 arch.
Runs ok if --arch=x86_64 is specified

**Comment by buggins** [comment] 2015-11-11 12:00
Probably fixed.
At least working for me under dmd 2.068.2 for both --arch=x86 and --arch=x86_64

**Comment by enurlyx** [comment] 2015-11-11 23:29
I tested it again. My steps:
- updated dlangui
- updated dependencies
- cleaned project
- build x86 release version
- build x86_64 release version

Result:
- x86 fails with the same error
- x86_64 works

Versions:
- dmd 2.0.69.0
- dlangui 0.6.45

**Comment by buggins** [comment] 2015-11-12 06:16
Thanks. I see similar issue on linux (SEGV)

**Comment by buggins** [comment] 2015-11-12 07:43
it looks like I fixed this problem in 0.6.46

**Comment by enurlyx** [comment] 2015-11-12 23:58
Tested again, but the x86 release build still fails.
Version:
- dmd 2.0.69.0
- dlangui 0.6.47

I do not know how to debug D. But looking at the code it seems to crash while loading libfreetype-6.dll. Maybe some dependencies are missing on my system?

Analyzed your ui.log file that is generated with the debug build. The app finds the dll, but fails to load it and uses the fallback. This happens also in the x86_64 version:

```
DlangUI log file
2015-11-13 00:47:23.896 I  Log level changed to Trace
2015-11-13 00:47:23.896 I  Logger is initialized
2015-11-13 00:47:23.896 D  myWinMain()
2015-11-13 00:47:23.896 I  Current executable: C:\Users\enurlyx\Desktop\ScriptPad 2\scriptpad\
2015-11-13 00:47:23.897 I  Command line: 
2015-11-13 00:47:23.897 I  Command line params: []
2015-11-13 00:47:23.897 V  Creating platform
2015-11-13 00:47:23.897 V  Registering window class
2015-11-13 00:47:23.897 V  Initializing font manager
2015-11-13 00:47:23.897 V  Trying to init FreeType font manager
2015-11-13 00:47:23.897 V  Creating FreeTypeFontManager
2015-11-13 00:47:23.897 V  DerelictFT: Loading FreeType library
2015-11-13 00:47:23.897 V  DerelictFT: Missing symbols callback is registered
2015-11-13 00:47:23.908 E  Derelict: cannot load freetype shared library: Failed to load symbol FT_Init_FreeType from shared library libfreetype-6.dll
2015-11-13 00:47:23.909 E  Cannot create FreeTypeFontManager - falling back to win32
2015-11-13 00:47:23.909 I  Creating Win32FontManager
2015-11-13 00:47:23.909 I  Win32FontManager.init()
2015-11-13 00:47:23.909 D  registerFont(MonoSpace,SimSun-ExtB)
2015-11-13 00:47:23.909 D  registerFont(Serif,KodchiangUPC)
```

**Comment by buggins** [comment] 2015-11-25 08:28
It should work w/o freetype, too.
You can debug it with Visual Studio Community Edition + Visual D plugin.
See README for instructions

**Comment by buggins** [comment] 2015-12-03 12:14
Cannot reproduce on recent version 0.6.54.
Probably fixed.

**Comment by thedeemon** [comment] 2015-12-05 06:52
No, not fixed.
It's somehow related to 2.069.
I tried with 2.069.0 and 2.069.2, in release mode I get the same error when trying to run hello world or other examples. In debug mode it works fine. I tried dlangui versions master, 0.7.2 and 0.6.21. Same error everywhere.
However with 2.068.2 dlangui 0.7.2 (and 0.6.21, didn't test others) in release mode works just fine.

**Comment by thedeemon** [comment] 2015-12-05 10:44
Interestingly, if I follow "Windows development using VisualD" i.e. git clone all the dependencies in fresh versions and build the example in MSVC, it does work fine. Also, the executable size for helloworld is 1590K when I build in MSVC and 1923K when I build with dub (with dependencies fetched by dub).

So it seems like the issue is caused by one of dependencies and it's already fixed in master but not in the version dub fetches by dlangui's dub.json file.

**Comment by Maeriden** [comment] 2016-02-02 02:42
I have the same error on windows.

With "dub build --build=release" I think I traced the error back to derelict static ctors.
For example, checking "DerelictFT is null" in the FreeTypeFontManager ctor returns true. If I bypass this error and use Win32FontManager, the same error happens later for DerelictGL and DerelictGL3

With just "dub build" derelict seems to work fine, but the program crashes after the log line "compileShader: glsl = , type: GL_VERTEX_SHADER". I haven't investigated that yet.

dmd 2.070.0; windows x86_64; version dub ~master; no arch specified (I assume it defaults to x86)

**Comment by buggins** [comment] 2016-02-02 06:31
Windows, dmd 2.069-2 x64 release build works ok for me
$ cd examples/helloworld
$ dmd --version
DMD32 D Compiler v2.069.2
Copyright (c) 1999-2015 by Digital Mars written by Walter Bright
$ dub run --build=release --arch=x86_64

For 32bit (x86) build I see Access Violation

**Comment by buggins** [comment] 2016-02-02 06:32
$ dub run --build=release --arch=x86
Running .\bin\helloworld.exe
object.Error@(0): Access Violation

**Comment by buggins** [comment] 2016-02-02 06:41
Cannot reproduce it when building from Visual-D

**Comment by thedeemon** [comment] 2016-02-02 08:53
In Visual-D the "-O" flag is disabled by default. Open project settings and enable it to compile with optimization.

**Comment by buggins** [comment] 2016-02-02 09:22
Reproduced by enabling optimization in VisualD. But now it crashes VisualD as well :)

**Comment by buggins** [comment] 2016-02-02 10:28
Some strange behavior. It looks like shared static this() is not executed for derelict loaders

Even changing of shared static this to __gshared static this does not help:

__gshared DerelictFTLoader DerelictFT;

shared static this() {
    DerelictFT = new DerelictFTLoader();
}

==========>

__gshared DerelictFTLoader DerelictFT;

__gshared static this() {
    DerelictFT = new DerelictFTLoader();
}

**Comment by buggins** [comment] 2016-02-03 07:49
Looks like it's caused by i18n file changes - adding of synchronized / shared.

**Comment by buggins** [comment] 2016-02-03 08:17
I hope it's fixed in v0.7.60

**Closed by buggins** 2016-02-03 08:17 UTC
Labels: bug

**Comment by thedeemon** [comment] 2016-02-03 09:04
Yes, I was able to successfully build with -O -inline -release the example1 and it works fine now.

**Comment by buggins** [comment] 2016-10-24 13:26
thanks
