### ISSUE TITLE
Can't use FileDialog to save to a new file

### ISSUE THREAD

**Issue by TheGag96** [buggins/dlangui#321] opened 2016-12-24 07:40 UTC
Windows 8.1, compiling debug builds with DMD v2.072.1 for x86

I'm using a file dialog like this:

```D
auto flags  = FileDialogFlag.Save | DialogFlag.Modal | DialogFlag.Resizable;
auto dialog = new FileDialog(UIString("Save to file"d), mainWindow, null, flags);

//...

dialog.show();
```

For some reason, if I try to enter the name of a not-yet-existing file in the dialog box, `dialog.filename` will just be `C:\path\to\initial\dir\..` and not update to be what I typed in the box. Also, in the delegate assigned to `dialog.dialogResult`, the passed-in Action's `stringParam` will be empty (shouldn't it contain `dialog.filename`?)

**Comment by TheGag96** [comment] 2017-01-03 03:17
I ended up fixing filedlg.d myself. I'll make a pull request soon to see if you're alright with my solution!

**Comment by buggins** [comment] 2017-01-10 06:10
It would be great if you can send pull request.

**Comment by zhaopuming** [comment] 2017-01-22 12:50
I hit this problem as well, it is caused by not assigning the _filename property after typing.

**Comment by buggins** [comment] 2017-01-23 06:46
Merged pull request for allowing non-existing filename in file dialog.
Is issue fixed now?

**Comment by zhaopuming** [comment] 2017-01-23 09:22
The pull request has this:

```d
   if ((_flags & FileDialogFlag.Save) && !(_flags & FileDialogFlag.FileMustExist)) {
            _edFilename.contentChange = &onFilenameTyped;
   }
```

meaning that only when you're doing "save file as" it works.
But when creating a new file, not "save file as", it will not work.

**Closed** 2017-05-10 10:40 UTC
Labels: bug
