### ISSUE TITLE
editable - Range violation

### ISSUE THREAD

**Issue by joelcnz** [buggins/dlangui#534] opened 2018-01-08 07:58 UTC
dlangui 0.9.173

To make it happen, go to the end of the editable text and make the rectangle disappear (Right arrow key), then try to add a character, and boom! It happens when the rectangle around the line isn't visible. I'm guessing the rectangle shouldn't disappear while you're got the text area in focus.

018-01-08 20:40:46.433 D  updateTexture for cache page - setting image 1024x1024 tx=1
core.exception.RangeError@../../../.dub/packages/dlangui-0.9.173/dlangui/src/dlangui/core/editable.d(1146): Range violation
----------------
4   timelog                             0x00000001013d9c12 _d_arrayboundsp + 110
5   timelog                             0x00000001012c7828 void dlangui.core.editable.EditableContent.replaceRange(dlangui.core.editable.TextRange, dlangui.core.editable.TextRange, immutable(dchar)[][], dlangui.core.editable.EditStateMark[]) + 888
6   timelog                             0x00000001012c8280 bool dlangui.core.editable.EditableContent.performOperation(dlangui.core.editable.EditOperation, Object) + 728
7   timelog                             0x000000010137be8d bool dlangui.widgets.editors.EditWidgetBase.onKeyEvent(dlangui.core.events.KeyEvent) + 773
8   timelog                             0x0000000101353ac2 bool dlangui.platforms.common.platform.Window.dispatchKeyEvent(dlangui.core.events.KeyEvent) + 414
9   timelog                             0x000000010135ac46 bool dlangui.platforms.sdl.sdlapp.SDLWindow.processTextInput(const(char*)) + 218
10  timelog                             0x000000010135bc41 int dlangui.platforms.sdl.sdlapp.SDLPlatform.enterMessageLoop() + 1989
11  timelog                             0x000000010124999b UIAppMain + 123
12  timelog                             0x000000010135c544 int dlangui.platforms.sdl.sdlapp.sdlmain(immutable(char)[][]) + 856
13  timelog                             0x000000010135c0cb DLANGUImain + 31
14  timelog                             0x00000001011d0a3b _Dmain + 31
15  timelog                             0x00000001013ed1d7 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll().__lambda1() + 39
16  timelog                             0x00000001013ed0ff void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) + 31
17  timelog                             0x00000001013ed17c void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() + 44
18  timelog                             0x00000001013ed0ff void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) + 31
19  timelog                             0x00000001013ed06a _d_run_main + 458
20  timelog                             0x00000001011d0a65 main + 33
21  libdyld.dylib                       0x00007fffb885b234 start + 0
22  ???                                 0x0000000000000000 0x0 + 0
Program exited with code 1

**Comment by and3md** [comment] 2018-01-25 17:41
Can't reproduce do you have any example code?

**Comment by triplejam** [comment] 2018-04-11 01:50
@and3md I think it only causes the crash in a debug build. In release the caret kind of just moves across the line but not inserting anything.

**Comment by and3md** [comment] 2018-04-11 19:30
@triplejam I tried in debug and release. Can't reproduce. What are the steps to reproduce this error?

**Comment by triplejam** [comment] 2018-04-11 20:52
@and3md Basically you have some text in the last line of an editbox and then move the caret one spot beyond the final character, so that the caret jumps back to the start, and then insert a letter. The rectangle disappears when the caret goes back to start of the line but I think this is a side-effect. The program should crash in debug because of the range violation. If it doesn't crash though I wonder if there is some sort of undefined behavior going on underneath with the entered text. Or maybe certain dlangui builds are slightly different?

**Comment by and3md** [comment] 2018-04-12 16:05
@triplejam Thanks for the clarification. Now I can reproduce this :)

**Comment by GrimMaple** [comment] 2023-05-23 19:57
It appears this recieved a fix already -- closing.

**Closed by GrimMaple** 2023-05-23 19:57 UTC
Labels: bug
